package wiring

import (
	"log/slog"

	auditevent "github.com/AlphaBitCore/nexus-gateway/packages/agent/internal/observability/audit/event"
	"github.com/AlphaBitCore/nexus-gateway/packages/agent/internal/platform/api"
)

// OnFlowComplete records an audit event after a flow completes with full
// transfer statistics. Implements platform.FlowAuditor.
func (b *ConnectionBridge) OnFlowComplete(result api.FlowResult) {
	action := "passthrough"
	switch result.Decision {
	case api.DecisionInspect:
		action = "inspect"
	case api.DecisionDeny:
		action = "deny"
	}

	var policyRuleID string
	if result.PolicyRuleID != "" {
		policyRuleID = result.PolicyRuleID
	} else {
		b.policyMu.Lock()
		policyRuleID = b.policyResults[result.FlowID]
		delete(b.policyResults, result.FlowID)
		b.policyMu.Unlock()
	}

	slog.Debug("flow complete",
		"flowId", result.FlowID,
		"host", result.DstHost,
		"action", action,
		"latencyMs", result.DurationMs,
		"bytesIn", result.BytesIn,
		"bytesOut", result.BytesOut,
	)

	var errorCode, errorReason string
	switch {
	case result.Decision == api.DecisionDeny:
		errorCode = "POLICY_DENIED"
		errorReason = "request denied by policy"
		if policyRuleID != "" {
			errorReason = "request denied by policy rule " + policyRuleID
		}
	case result.BumpStatus == "BUMP_FAILED_PASSTHROUGH":
		errorCode = "BUMP_FAILED"
		errorReason = "TLS inspection unavailable, connection passed through"
	}

	// A FlowResult comes only from a non-bumped flow (passthrough / deny /
	// inspect-fallback), so it carries no decrypted-HTTP fields (method, path,
	// provider, tokens, hook decision). Those are written per-HTTP-request from
	// inside tlsbump for bumped inspect flows, on a separate path. TraceID
	// equals FlowID so compliance-proxy and ai-gateway events generated by this
	// flow join across services via the shared trace id.
	e := auditevent.Event{
		ID:               result.FlowID,
		TraceID:          result.FlowID,
		Timestamp:        result.StartedAt,
		SourceIP:         result.SrcIP,
		SourceProcess:    result.Process.Name,
		OSUser:           result.Process.User,
		TargetHost:       result.DstHost,
		DestIP:           result.DstIP,
		DestPort:         result.DstPort,
		Action:           action,
		PolicyRuleID:     policyRuleID,
		BumpStatus:       result.BumpStatus,
		BytesIn:          result.BytesIn,
		BytesOut:         result.BytesOut,
		LatencyMs:        result.DurationMs,
		ErrorCode:        errorCode,
		ErrorReason:      errorReason,
		UpstreamTtfbMs:   result.UpstreamTtfbMs,
		UpstreamTotalMs:  result.UpstreamTotalMs,
		LatencyBreakdown: result.LatencyBreakdown,
	}
	// A FlowResult carries no decrypted HTTP body — bumped inspect flows
	// capture + spill bodies per-request from inside tlsbump (which writes
	// the SpillRef onto the canonical audit event), and passthrough/deny
	// flows have no HTTP layer to capture. So OnFlowComplete records
	// transport-level metadata only.
	if err := b.AuditQueue.Record(e); err != nil {
		slog.Error("failed to record flow audit event", "flowId", result.FlowID, "error", err)
	}
}
