-- 2026-05-21 — Second script in the cost-recompute series.
--
-- Run AFTER recompute_traffic_event_costs_2026_05_21.sql.
--
-- =====================================================================
-- WHAT THIS DOES
-- =====================================================================
--   After traffic_event.estimated_cost_usd was recomputed in place, the
--   metric_rollup_* tables hold stale SUMs (per-dimension cost totals
--   based on the pre-recompute values). This script invalidates the
--   affected buckets so the rollup cron jobs re-aggregate from the now-
--   corrected raw rows.
--
-- =====================================================================
-- PROD-SAFE STRATEGY
-- =====================================================================
--   Naively, dropping ALL rollup rows + resetting watermark to the
--   earliest traffic_event timestamp would force the rollup cron to
--   replay every 5-min bucket since service launch. On a year-old prod
--   that's ~100k buckets — multiple hours of catch-up.
--
--   Instead, this script:
--     1) Computes the time window of affected rows (= every row touched
--        by the recompute = essentially the full traffic history).
--     2) DELETEs rollup_5m + rollup_1h + rollup_1d + rollup_1mo rows
--        whose bucket boundary falls inside that window.
--     3) Resets rollup-5m / merge-1h / merge-1d / merge-1mo watermarks
--        to the earliest affected bucket so cron picks up cleanly.
--     4) Same for thing-rollup-5m + thing-merge-1h/1d/1mo.
--
--   The cron job processes ONE bucket per tick (default 1 min interval
--   for rollup-5m, 5 min for merge-1h, 1h for merge-1d). On a prod
--   backlog of N buckets:
--     - rollup-5m: 1 bucket per minute  → 60 buckets/hour
--     - merge-1h:  1 bucket per 5 min   → 12 buckets/hour
--     - merge-1d:  1 bucket per 1 hour  → 24 buckets/day
--
--   For a 1-month backlog (~8640 5-min buckets), the rollup-5m job
--   needs ~6 days to catch up at default cadence. If that's too slow,
--   operators may increase the interval temporarily via yaml + restart
--   Hub. The merge tiers cascade from rollup_5m so they catch up after.
--
-- =====================================================================
-- IF YOU WANT TO LIMIT THE WINDOW
-- =====================================================================
--   Edit the `affected_window` CTE below to only invalidate a recent
--   window (e.g., last 30 days) if older historical drift is tolerable.
--   See the WHERE clause marked HISTORICAL_CUTOFF.
--
-- =====================================================================
-- ROLLBACK
-- =====================================================================
--   None — rollup rows are derived data; they get regenerated by cron.
--
-- =====================================================================

\set ON_ERROR_STOP on

BEGIN;

-- Step 1: scope the window of rows actually touched by the recompute.
-- HISTORICAL_CUTOFF: change this to e.g. `now() - INTERVAL '30 days'`
-- if you only want to invalidate recent rollups.
WITH affected_window AS (
    SELECT
        -- Floor to nearest 5-min bucket: truncate to minute then subtract
        -- the modulo-5 remainder. e.g. 16:16:16 → 16:16 → 16:15.
        date_trunc('minute', MIN(te.timestamp))
            - (EXTRACT(MINUTE FROM MIN(te.timestamp))::int % 5) * INTERVAL '1 minute' AS earliest_bucket_5m,
        MAX(te.timestamp) AS latest_event
    FROM traffic_event te
    WHERE te.routed_model_id IS NOT NULL
      AND te.prompt_tokens IS NOT NULL
      -- HISTORICAL_CUTOFF: uncomment + tune to limit scope
      -- AND te.timestamp >= now() - INTERVAL '30 days'
)
SELECT
    earliest_bucket_5m,
    latest_event,
    EXTRACT(EPOCH FROM (latest_event - earliest_bucket_5m)) / 300 AS approx_5m_buckets
FROM affected_window
\gset

\echo ----
\echo Earliest affected 5m bucket: :earliest_bucket_5m
\echo Approximate 5m buckets to re-aggregate: :approx_5m_buckets
\echo ----

-- Step 2: invalidate rollup tiers (use the same bucket boundary).
-- Each DELETE limited to the affected window so unchanged historical
-- rollups stay intact (defensive against the script being re-run later
-- with a narrower HISTORICAL_CUTOFF).

DELETE FROM metric_rollup_5m
 WHERE "bucketStart" >= :'earliest_bucket_5m';

DELETE FROM metric_rollup_1h
 WHERE "bucketStart" >= date_trunc('hour', TIMESTAMP :'earliest_bucket_5m');

DELETE FROM metric_rollup_1d
 WHERE "bucketStart" >= date_trunc('day', TIMESTAMP :'earliest_bucket_5m');

DELETE FROM metric_rollup_1mo
 WHERE "bucketStart" >= date_trunc('month', TIMESTAMP :'earliest_bucket_5m');

-- Per-thing rollup tiers — same windowing.
DELETE FROM thing_metric_rollup_5m
 WHERE "bucketStart" >= :'earliest_bucket_5m';

DELETE FROM thing_metric_rollup_1h
 WHERE "bucketStart" >= date_trunc('hour', TIMESTAMP :'earliest_bucket_5m');

DELETE FROM thing_metric_rollup_1d
 WHERE "bucketStart" >= date_trunc('day', TIMESTAMP :'earliest_bucket_5m');

DELETE FROM thing_metric_rollup_1mo
 WHERE "bucketStart" >= date_trunc('month', TIMESTAMP :'earliest_bucket_5m');

-- Step 3: reset watermarks so the rollup cron re-processes those buckets.
-- We set watermark = earliest_bucket_5m - 5min so the loop's
-- `bucket := watermark + 5m` starts at earliest_bucket_5m.

UPDATE rollup_watermark
   SET watermark = (TIMESTAMP :'earliest_bucket_5m' - INTERVAL '5 minutes')::timestamptz,
       "updatedAt" = now()
 WHERE "jobName" IN ('rollup-5m', 'thing-rollup-5m');

UPDATE rollup_watermark
   SET watermark = (date_trunc('hour',  TIMESTAMP :'earliest_bucket_5m') - INTERVAL '1 hour')::timestamptz,
       "updatedAt" = now()
 WHERE "jobName" IN ('merge-1h', 'thing-merge-1h');

UPDATE rollup_watermark
   SET watermark = (date_trunc('day',   TIMESTAMP :'earliest_bucket_5m') - INTERVAL '1 day')::timestamptz,
       "updatedAt" = now()
 WHERE "jobName" IN ('merge-1d', 'thing-merge-1d');

-- merge-1mo is calendar-month aligned; the merge job handles back-fill
-- by detecting closed months itself. Resetting watermark to the start
-- of the affected month is enough.
UPDATE rollup_watermark
   SET watermark = date_trunc('month', TIMESTAMP :'earliest_bucket_5m')::timestamptz,
       "updatedAt" = now()
 WHERE "jobName" IN ('merge-1mo', 'thing-merge-1mo');

COMMIT;

-- Final state report
SELECT "jobName", watermark AT TIME ZONE 'UTC' AS watermark_utc, "updatedAt" AT TIME ZONE 'UTC' AS updated_utc
  FROM rollup_watermark
 ORDER BY "jobName";
