package openapigen

import (
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

// generatedHeader is prepended to every emitted YAML file so readers and the
// audit skill know the file is machine-produced and how to refresh it.
const generatedHeader = "# Generated by `nexus openapi-gen` from control-plane source. DO NOT hand-edit\n" +
	"# structural fields (paths/verbs/types) — they are overwritten on regen. The\n" +
	"# openapi-review skill enriches descriptions/examples/enums in place.\n"

// Generate runs the full pipeline: load the control-plane packages, discover
// admin routes, assemble one OpenAPI document per resource kind, and write them
// (plus an index catalog) to opts.OutDir. It returns a Report even on a partial
// run so callers can see what was unresolved.
func Generate(opts Options) (*Report, error) {
	opts.withDefaults()
	rep := &Report{}

	l, err := loadControlPlane(opts.SrcDir, opts.Patterns, opts.Env)
	if err != nil {
		return rep, err
	}
	routes := l.discoverRoutes(opts, rep)
	assignOperationIDs(routes, opts.BasePrefix) // unique operationId per kind (one handler may serve several routes)
	docs := buildDocuments(routes, opts, rep)

	if opts.OutDir == "" {
		return rep, fmt.Errorf("OutDir is required")
	}
	if err := os.MkdirAll(opts.OutDir, 0o755); err != nil {
		return rep, fmt.Errorf("create out dir: %w", err)
	}

	for _, d := range docs {
		path := filepath.Join(opts.OutDir, d.Kind+".yaml")
		if err := writeYAML(path, d.Doc); err != nil {
			return rep, err
		}
		rep.Kinds = append(rep.Kinds, d.Kind)
		rep.Routes += len(d.Routes)
		rep.FilesWritten = append(rep.FilesWritten, path)
	}

	indexPath := filepath.Join(opts.OutDir, "_index.yaml")
	if err := writeYAML(indexPath, buildIndex(docs, opts)); err != nil {
		return rep, err
	}
	rep.FilesWritten = append(rep.FilesWritten, indexPath)

	return rep, nil
}

// buildIndex assembles the resource-kind catalog the resource_kinds tool reads:
// one entry per kind listing its file and every operation with method, path,
// operationId, tier and IAM action.
func buildIndex(docs []document, opts Options) *omap {
	idx := newOMap()
	idx.Set("generatedBy", "openapigen")
	idx.Set("version", opts.Version)
	idx.Set("basePrefix", opts.BasePrefix)

	var kinds []any
	for _, d := range docs {
		var ops []any
		for _, r := range d.Routes {
			oapiPath, _ := echoToOpenAPIPath(r.Path)
			op := newOMap().
				Set("method", r.Method).
				Set("path", oapiPath).
				Set("operationId", r.OperationID).
				Set("tier", string(r.Tier))
			op.SetIf(r.IAMAction != "", "iamAction", r.IAMAction)
			ops = append(ops, op)
		}
		kinds = append(kinds, newOMap().
			Set("kind", d.Kind).
			Set("file", d.Kind+".yaml").
			Set("operations", ops))
	}
	idx.Set("kinds", kinds)
	return idx
}

// writeYAML marshals v to YAML with the generated header and writes it atomically.
func writeYAML(path string, v any) error {
	out, err := yaml.Marshal(v)
	if err != nil {
		return fmt.Errorf("marshal %s: %w", path, err)
	}
	data := append([]byte(generatedHeader), out...)
	if err := os.WriteFile(path, data, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}
