//go:build linux

package platform

import (
	"bufio"
	"os"
	"strings"
)

// hardwareUUID returns /etc/machine-id (systemd-managed). Stable across
// reboots; regenerated by `systemd-machine-id-setup --commit` (rare on
// long-lived hosts). Falls back to /var/lib/dbus/machine-id where
// systemd is absent. Empty on read failure.
func hardwareUUID() string {
	for _, path := range []string{"/etc/machine-id", "/var/lib/dbus/machine-id"} {
		data, err := os.ReadFile(path)
		if err == nil {
			s := strings.TrimSpace(string(data))
			if s != "" {
				return s
			}
		}
	}
	return ""
}

// hardwareSerial returns DMI product serial (when readable). On most
// distros this requires root; we return empty on permission denied
// rather than fail the whole capture. Common path on systemd hosts is
// /sys/class/dmi/id/product_serial.
func hardwareSerial() string {
	data, err := os.ReadFile("/sys/class/dmi/id/product_serial")
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(data))
}

// hardwareModel returns the DMI product name (e.g. "20XK0040US"). Empty
// when the DMI sysfs file is unreadable (containers without /sys, or hosts
// that disabled SMBIOS).
func hardwareModel() string {
	data, err := os.ReadFile("/sys/class/dmi/id/product_name")
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(data))
}

// cpuBrandString reads /proc/cpuinfo and returns the first "model name"
// field, e.g. "Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz". Empty
// on read failure or when the field is absent (ARM hosts where this
// field uses different keys; not relevant for the fleet today but
// worth knowing).
func cpuBrandString() string {
	f, err := os.Open("/proc/cpuinfo")
	if err != nil {
		return ""
	}
	defer func() { _ = f.Close() }()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()
		if !strings.HasPrefix(line, "model name") {
			continue
		}
		idx := strings.IndexByte(line, ':')
		if idx < 0 {
			return ""
		}
		return strings.TrimSpace(line[idx+1:])
	}
	return ""
}
