//go:build darwin

// Package bundles inspects the macOS host-app and system-extension bundle
// version stamps so a single log line makes version mismatches obvious.
package bundles

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// BundleVersions captures the version stamps of every macOS-side artifact
// that participates in agent NE plumbing, so a single log line / CLI dump
// makes a version mismatch obvious. Background: macOS skips system-extension
// replacement when CFBundleVersion does not strictly increase, leaving the
// freshly installed extension binary on disk while macOS keeps loading the
// cached old one from /Library/SystemExtensions/<UUID>/. Without this
// inventory the only way to spot the mismatch is to compare file mtimes,
// which is exactly the class of mismatch this inventory makes obvious.
type BundleVersions struct {
	HostApp       BundleStamp `json:"host_app"`
	ExtensionDisk BundleStamp `json:"extension_disk"`
	ExtensionLive BundleStamp `json:"extension_live"`
}

type BundleStamp struct {
	Path                 string `json:"path,omitempty"`
	CFBundleShortVersion string `json:"short_version,omitempty"`
	CFBundleVersion      string `json:"build_number,omitempty"`
	Mtime                string `json:"mtime,omitempty"`
	Note                 string `json:"note,omitempty"`
}

// InspectBundles inspects the three on-disk Info.plists relevant to the
// macOS agent: the host .app, the bundled .systemextension on disk, and
// the system-extension that macOS actually copied into
// /Library/SystemExtensions/<UUID>/ when the user approved an install.
// Any I/O failure is reported in BundleStamp.Note rather than thrown so
// the daemon can still log a partial inventory.
func InspectBundles() BundleVersions {
	host := "/Applications/NexusAgent.app/Contents/Info.plist"
	extDisk := "/Applications/NexusAgent.app/Contents/Library/SystemExtensions/" +
		"com.nexus-gateway.agent.extension.systemextension/Contents/Info.plist"
	extLive := findLiveExtensionInfoPlist()

	return BundleVersions{
		HostApp:       readBundleStamp(host, ""),
		ExtensionDisk: readBundleStamp(extDisk, ""),
		ExtensionLive: readBundleStamp(extLive, "macOS-cached copy under /Library/SystemExtensions/<UUID>/"),
	}
}

// findLiveExtensionInfoPlist walks /Library/SystemExtensions/<UUID>/ to
// locate the currently-installed copy of our system extension. macOS
// stages each approved extension in a UUID directory whose name we do
// not control — we identify ours by bundle id suffix.
//
// Multiple UUID dirs can hold our extension after an upgrade: macOS
// keeps stale copies around until a later GC pass. Picking the first
// (alphabetical) one returns the OLDEST install plist and produces
// false VERSION MISMATCH warnings while the actual running provider
// is the newest. Prefer the directory whose Info.plist has the latest
// mtime so the inventory matches what macOS actually loaded.
func findLiveExtensionInfoPlist() string {
	const root = "/Library/SystemExtensions"
	const target = "com.nexus-gateway.agent.extension.systemextension/Contents/Info.plist"

	entries, err := os.ReadDir(root)
	if err != nil {
		return ""
	}
	var best string
	var bestMtime int64
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		candidate := filepath.Join(root, e.Name(), target)
		info, err := os.Stat(candidate)
		if err != nil {
			continue
		}
		mt := info.ModTime().UnixNano()
		if best == "" || mt > bestMtime {
			best = candidate
			bestMtime = mt
		}
	}
	return best
}

// readBundleStamp parses CFBundleVersion + CFBundleShortVersionString out
// of an Info.plist via plain string scan. The XML is generated by
// PlistBuddy / Xcode and follows a stable pattern: <key>X</key> followed
// by a <string>...</string> on the next non-whitespace span. This avoids
// dragging in a plist parser for what's a 5-line regex job; if the parse
// shape changes upstream we'll see "<missing>" in the stamp and know to
// revisit.
func readBundleStamp(path, defaultNote string) BundleStamp {
	stamp := BundleStamp{Path: path, Note: defaultNote}
	if path == "" {
		stamp.Note = "not found on disk"
		return stamp
	}
	info, statErr := os.Stat(path)
	if statErr != nil {
		stamp.Note = fmt.Sprintf("stat failed: %v", statErr)
		return stamp
	}
	stamp.Mtime = info.ModTime().UTC().Format("2006-01-02T15:04:05Z")
	data, err := os.ReadFile(path)
	if err != nil {
		stamp.Note = fmt.Sprintf("read failed: %v", err)
		return stamp
	}
	stamp.CFBundleShortVersion = extractPlistString(string(data), "CFBundleShortVersionString")
	stamp.CFBundleVersion = extractPlistString(string(data), "CFBundleVersion")
	if stamp.CFBundleVersion == "" {
		stamp.CFBundleVersion = "<missing>"
	}
	if stamp.CFBundleShortVersion == "" {
		stamp.CFBundleShortVersion = "<missing>"
	}
	return stamp
}

// extractPlistString finds the first <string>...</string> following the
// requested <key>...</key>. Returns "" when not present. Tolerant of
// whitespace + newlines between the key and string elements.
func extractPlistString(plist, key string) string {
	keyTag := "<key>" + key + "</key>"
	idx := strings.Index(plist, keyTag)
	if idx < 0 {
		return ""
	}
	rest := plist[idx+len(keyTag):]
	open := strings.Index(rest, "<string>")
	close := strings.Index(rest, "</string>")
	if open < 0 || close <= open+8 {
		return ""
	}
	return strings.TrimSpace(rest[open+8 : close])
}
