package systembundles

import "strings"

// RenderSwift produces the full contents of SystemBundles.generated.swift from
// ProtectedBundles. The emitted matcher mirrors Go related()/normalize()
// semantics EXACTLY so the NE fast-decline floor can never drift from this Go
// SSOT. It is exported so a golden test in this package can assert the
// committed generated file is up to date (CI catches a stale checkout) without
// shelling out to the gen binary.
//
// Matching contract reproduced in Swift:
//   - normalize(candidate): lowercase, trim surrounding whitespace, trim
//     trailing dots — same as Go normalize().
//   - covers(candidate): true iff, for some protected entry p, the pair is in
//     an equal / ancestor / descendant relationship — same as Go related():
//     c == p || c.hasPrefix(p+".") || p.hasPrefix(c+".").
//   - protected entries are emitted lowercase (the normalize() contract), so
//     an over-broad "com.apple" catches every com.apple.* and the
//     "com.apple.kerberos" namespace catches com.apple.kerberos.kdc.
func RenderSwift() string {
	var b strings.Builder

	b.WriteString(`// Code generated by packages/shared/policy/systembundles/internal/gen; DO NOT EDIT.
//
// Source of truth: packages/shared/policy/systembundles (ProtectedBundles +
// normalize()/related()). Regenerate with:
//   cd packages/shared && go generate ./policy/systembundles/...
//
// This is the macOS NE copy of the system-protection FLOOR: critical macOS
// networking / push / continuity / time / location / authentication daemons
// whose UDP must NEVER be claimed by the proxy (CLAUDE.md NE rule 5). It is a
// HARDCODED floor on both the Go and Swift sides — intentionally NOT
// shadow-controllable. That immutability is the SEC-M8-01 A3-defense: an
// attacker who can push the agent_settings shadow cannot widen the kill-list
// to close UDP for a system daemon, because the floor is compiled in.
//
// SystemBundles.covers(_:) reproduces the Go related()/normalize() semantics
// EXACTLY (lowercase-normalized equal / ancestor / descendant match), so the
// two copies can never drift (F-0392 / F-0368 closed by codegen).

import Foundation

enum SystemBundles {
    /// The protected floor, lowercase to match the normalize() contract.
    static let protected: Set<String> = [
`)

	for _, p := range ProtectedBundles {
		b.WriteString("        ")
		b.WriteString(swiftQuote(normalize(p)))
		b.WriteString(",\n")
	}

	b.WriteString(`    ]

    /// normalize mirrors Go normalize(): lowercase, trim surrounding
    /// whitespace, then trim any trailing dots (so a "com.apple." typo
    /// normalizes to the over-broad ancestor "com.apple").
    private static func normalize(_ s: String) -> String {
        var n = s.trimmingCharacters(in: .whitespaces).lowercased()
        while n.hasSuffix(".") {
            n.removeLast()
        }
        return n
    }

    /// covers reports whether bundleId is — or sits in an ancestor/descendant
    /// namespace relationship with — a protected system daemon. Mirrors Go
    /// related(): c == p || c.hasPrefix(p+".") || p.hasPrefix(c+"."). Used by
    /// handleNewFlow to fast-decline (return false = pass-through = fail-open)
    /// so a protected daemon's UDP is never claimed regardless of port.
    static func covers(_ bundleId: String) -> Bool {
        let c = normalize(bundleId)
        if c.isEmpty {
            return false
        }
        for p in protected {
            if c == p || c.hasPrefix(p + ".") || p.hasPrefix(c + ".") {
                return true
            }
        }
        return false
    }
}
`)

	return b.String()
}

// swiftQuote wraps s in double quotes. ProtectedBundles entries are reverse-DNS
// bundle ids / bare process names — no embedded quotes or backslashes — so a
// plain wrap is correct; we still escape defensively to keep the generator
// honest if an entry ever changes shape.
func swiftQuote(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`)
	return `"` + r.Replace(s) + `"`
}
