package systembundles

import (
	"os"
	"path/filepath"
	"reflect"
	"runtime"
	"strings"
	"testing"
)

// TestCovers asserts the equal/ancestor/descendant rule: a kill-list entry is
// flagged iff honoring it would close UDP for a protected system daemon, while
// ordinary app bundles (legitimate QUIC-fallback targets) are allowed.
func TestCovers(t *testing.T) {
	cases := []struct {
		name      string
		entry     string
		wantOK    bool
		wantUnder string // the protected bundle it would close (when wantOK)
	}{
		// exact system daemon — the direct kill
		{"exact mdnsresponder bundle", "com.apple.mDNSResponder", true, "com.apple.mdnsresponder"},
		{"exact apsd push", "com.apple.apsd", true, "com.apple.apsd"},
		{"exact bare ntpd", "ntpd", true, "ntpd"},
		// finding's named-missing daemons (the NE 13-set omitted these)
		{"identityservicesd (iMessage)", "com.apple.identityservicesd", true, "com.apple.identityservicesd"},
		{"rapportd (Continuity)", "com.apple.rapportd", true, "com.apple.rapportd"},
		// over-broad ancestor prefix — the headline attack
		{"bare com.apple namespace", "com.apple", true, ""},
		{"com.apple. trailing dot typo", "com.apple.", true, ""},
		// child of a protected namespace (Kerberos.*)
		{"kerberos child kdc", "com.apple.Kerberos.kdc", true, "com.apple.kerberos"},
		{"kerberos child digest", "com.apple.Kerberos.digestProxy", true, "com.apple.kerberos"},
		// case-insensitive
		{"uppercased system bundle", "COM.APPLE.CONFIGD", true, "com.apple.configd"},
		// legitimate app targets — MUST be allowed
		{"safari (legit QUIC app)", "com.apple.Safari", false, ""},
		{"chrome", "com.google.Chrome", false, ""},
		{"firefox", "org.mozilla.firefox", false, ""},
		{"an electron AI app", "com.openai.chat", false, ""},
		{"empty", "", false, ""},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			under, ok := Covers(tc.entry)
			if ok != tc.wantOK {
				t.Fatalf("Covers(%q) ok=%v, want %v (under=%q)", tc.entry, ok, tc.wantOK, under)
			}
			if tc.wantOK && tc.wantUnder != "" && under != tc.wantUnder {
				t.Errorf("Covers(%q) protected=%q, want %q", tc.entry, under, tc.wantUnder)
			}
		})
	}
}

// TestFilter asserts the daemon-side strip keeps legitimate targets and drops
// the protected ones, preserving order, for the defense-in-depth path.
func TestFilter(t *testing.T) {
	in := []string{"com.google.Chrome", "com.apple", "com.apple.Safari", "com.apple.apsd", "org.mozilla.firefox"}
	clean, stripped := Filter(in)
	wantClean := []string{"com.google.Chrome", "com.apple.Safari", "org.mozilla.firefox"}
	wantStripped := []string{"com.apple", "com.apple.apsd"}
	if !reflect.DeepEqual(clean, wantClean) {
		t.Errorf("clean = %v, want %v", clean, wantClean)
	}
	if !reflect.DeepEqual(stripped, wantStripped) {
		t.Errorf("stripped = %v, want %v", stripped, wantStripped)
	}
}

// TestFilter_AllSafe returns a nil stripped slice when nothing is protected.
func TestFilter_AllSafe(t *testing.T) {
	clean, stripped := Filter([]string{"com.google.Chrome", "com.apple.Safari"})
	if len(stripped) != 0 {
		t.Errorf("stripped = %v, want none", stripped)
	}
	if len(clean) != 2 {
		t.Errorf("clean = %v, want 2 entries", clean)
	}
}

// generatedSwiftPath resolves the committed SystemBundles.generated.swift in
// the NE extension dir, anchored to this test file so it is cwd-independent.
func generatedSwiftPath(t *testing.T) string {
	t.Helper()
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("cannot resolve test source path")
	}
	// thisFile = .../packages/shared/policy/systembundles/systembundles_test.go
	packagesDir := filepath.Clean(filepath.Join(filepath.Dir(thisFile), "..", "..", ".."))
	return filepath.Join(packagesDir,
		"agent", "platform", "darwin", "NexusAgent", "NexusAgentExtension",
		"SystemBundles.generated.swift")
}

// TestRenderSwift_Content asserts the rendered Swift carries the DO-NOT-EDIT
// header and every protected entry (lowercase-normalized), with a covers()
// matcher reproducing the Go related() rule. This is the business contract the
// NE relies on: the floor and the matcher both ship in the generated file.
func TestRenderSwift_Content(t *testing.T) {
	out := RenderSwift()
	if !strings.Contains(out, "// Code generated by packages/shared/policy/systembundles/internal/gen; DO NOT EDIT.") {
		t.Error("generated Swift missing DO-NOT-EDIT codegen header")
	}
	if !strings.Contains(out, "static func covers(_ bundleId: String) -> Bool") {
		t.Error("generated Swift missing covers() matcher")
	}
	// related() rule must be reproduced verbatim in the Swift matcher.
	if !strings.Contains(out, `c == p || c.hasPrefix(p + ".") || p.hasPrefix(c + ".")`) {
		t.Error("generated Swift covers() does not mirror Go related() equal/ancestor/descendant rule")
	}
	for _, p := range ProtectedBundles {
		want := swiftQuote(normalize(p))
		if !strings.Contains(out, want) {
			t.Errorf("generated Swift missing protected entry %s", want)
		}
		// every emitted entry must be lowercase (normalize() contract)
		if want != strings.ToLower(want) {
			t.Errorf("protected entry %s is not lowercase-normalized", want)
		}
	}
}

// TestGeneratedSwiftUpToDate is the staleness/golden gate: the committed
// SystemBundles.generated.swift MUST byte-match what RenderSwift() produces
// from the current ProtectedBundles. A drift here means someone changed the Go
// SSOT (or hand-edited the generated file) without rerunning
// `go generate ./policy/systembundles/...` — CI fails so the stale NE floor
// never ships.
func TestGeneratedSwiftUpToDate(t *testing.T) {
	path := generatedSwiftPath(t)
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read committed generated Swift %s: %v", path, err)
	}
	if string(got) != RenderSwift() {
		t.Fatalf("%s is stale — rerun `cd packages/shared && go generate ./policy/systembundles/...`", path)
	}
}
