package thingstore

import (
	"context"
	"encoding/json"
	"fmt"
	"time"
)

// ConfigChangeEvent represents an admin-initiated config change audit record.
// Rows are insert-only; never updated or deleted.
type ConfigChangeEvent struct {
	ID                string          `json:"id"`
	Timestamp         time.Time       `json:"timestamp"`
	ThingType         string          `json:"thingType"`
	ConfigKey         string          `json:"configKey"`
	Action            string          `json:"action"`
	ActorID           string          `json:"actorId"`
	ActorName         string          `json:"actorName"`
	NewState          json.RawMessage `json:"newState"`
	NewVersion        int64           `json:"newVersion"`
	SourceIP          *string         `json:"sourceIp,omitempty"`
	EmergencyOverride bool            `json:"emergencyOverride"`
}

// ListConfigChangeEventsParams holds filter and pagination params for ListConfigChangeEvents.
type ListConfigChangeEventsParams struct {
	ThingType string
	ConfigKey string
	ActorID   string
	Since     *time.Time
	Until     *time.Time
	Limit     int
	Offset    int
}

// InsertConfigChangeEvent appends a new audit record. The id is generated by the DB.
func (store *Store) InsertConfigChangeEvent(ctx context.Context, e ConfigChangeEvent) error {
	query := `
		INSERT INTO config_change_event
			(thing_type, config_key, action, actor_id, actor_name, new_state, new_version, source_ip, emergency_override)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)`
	_, err := store.pool.Exec(ctx, query,
		e.ThingType, e.ConfigKey, e.Action,
		e.ActorID, e.ActorName,
		e.NewState, e.NewVersion,
		e.SourceIP,
		e.EmergencyOverride,
	)
	if err != nil {
		return fmt.Errorf("insert config change event: %w", err)
	}
	return nil
}

// ListConfigChangeEvents returns a paginated, filterable slice of config change events.
// Returns the events and the total matching row count.
func (store *Store) ListConfigChangeEvents(ctx context.Context, p ListConfigChangeEventsParams) ([]ConfigChangeEvent, int, error) {
	if p.Limit <= 0 {
		p.Limit = 20
	}

	where := " WHERE 1=1"
	args := []any{}
	n := 1

	if p.ThingType != "" {
		where += fmt.Sprintf(" AND thing_type = $%d", n)
		args = append(args, p.ThingType)
		n++
	}
	if p.ConfigKey != "" {
		where += fmt.Sprintf(" AND config_key = $%d", n)
		args = append(args, p.ConfigKey)
		n++
	}
	if p.ActorID != "" {
		where += fmt.Sprintf(" AND actor_id = $%d", n)
		args = append(args, p.ActorID)
		n++
	}
	if p.Since != nil {
		where += fmt.Sprintf(" AND timestamp >= $%d", n)
		args = append(args, *p.Since)
		n++
	}
	if p.Until != nil {
		where += fmt.Sprintf(" AND timestamp <= $%d", n)
		args = append(args, *p.Until)
		n++
	}

	// Total count (same filters, no limit/offset).
	var total int
	if err := store.pool.QueryRow(ctx, "SELECT COUNT(*) FROM config_change_event"+where, args...).Scan(&total); err != nil {
		return nil, 0, fmt.Errorf("count config change events: %w", err)
	}

	// Paginated rows.
	dataQuery := `
		SELECT id, timestamp, thing_type, config_key, action, actor_id, actor_name, new_state, new_version, source_ip, emergency_override
		FROM config_change_event` +
		where +
		fmt.Sprintf(" ORDER BY timestamp DESC LIMIT $%d OFFSET $%d", n, n+1)
	args = append(args, p.Limit, p.Offset)

	rows, err := store.pool.Query(ctx, dataQuery, args...)
	if err != nil {
		return nil, 0, fmt.Errorf("list config change events: %w", err)
	}
	defer rows.Close()

	var result []ConfigChangeEvent
	for rows.Next() {
		var e ConfigChangeEvent
		if err := rows.Scan(
			&e.ID, &e.Timestamp, &e.ThingType, &e.ConfigKey,
			&e.Action, &e.ActorID, &e.ActorName,
			&e.NewState, &e.NewVersion, &e.SourceIP, &e.EmergencyOverride,
		); err != nil {
			return nil, 0, fmt.Errorf("scan config change event: %w", err)
		}
		result = append(result, e)
	}
	if err := rows.Err(); err != nil {
		return nil, 0, fmt.Errorf("iterate config change events: %w", err)
	}
	return result, total, nil
}

// GetLatestConfigChangeEvent returns the single most recent audit row for a
// given (thingType, configKey). Returns (nil, nil) when no rows match so
// callers can treat "never edited" as a non-error absence. Used by the
// admin /things/{id}/applied-config BFF to surface a per-key "lastChange"
// stanza without paginating the full audit history.
func (store *Store) GetLatestConfigChangeEvent(ctx context.Context, thingType, configKey string) (*ConfigChangeEvent, error) {
	query := `
		SELECT id, timestamp, thing_type, config_key, action, actor_id, actor_name, new_state, new_version, source_ip, emergency_override
		FROM config_change_event
		WHERE thing_type = $1 AND config_key = $2
		ORDER BY timestamp DESC
		LIMIT 1`
	var e ConfigChangeEvent
	err := store.pool.QueryRow(ctx, query, thingType, configKey).Scan(
		&e.ID, &e.Timestamp, &e.ThingType, &e.ConfigKey,
		&e.Action, &e.ActorID, &e.ActorName,
		&e.NewState, &e.NewVersion, &e.SourceIP, &e.EmergencyOverride,
	)
	if err != nil {
		if err.Error() == "no rows in result set" {
			return nil, nil
		}
		return nil, fmt.Errorf("get latest config change event: %w", err)
	}
	return &e, nil
}
